name: checkbox-edgexfoundry
summary: Checkbox tests for EdgeX Foundry
description: |
  Collection of EdgeX Foundry tests to be run on Snappy devices.
version: '2.0'
grade: stable
confinement: strict

base: core20

plugs:
  checkbox-runtime:
    interface: content
    target: $SNAP/checkbox-runtime
    default-provider: checkbox20
  provider-resource:
    interface: content
    target: $SNAP/providers/checkbox-provider-resource
    default-provider: checkbox20
  provider-checkbox:
    interface: content
    target: $SNAP/providers/checkbox-provider-base
    default-provider: checkbox20

layout:
    /usr/share/git-core:
      bind: $SNAP_COMMON/usr/share/git-core

apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
    plugs: &standard [home, network-bind, hardware-observe,
      mount-observe, network-manager, pulseaudio, serial-port,
      system-observe]
  fuji:
    command-chain: [bin/wrapper_local]
    command: bin/fuji
    plugs: *standard
  geneva:
    command-chain: [bin/wrapper_local]
    command: bin/geneva
    plugs: *standard
  hanoi:
    command-chain: [bin/wrapper_local]
    command: bin/hanoi
    plugs: *standard
  ireland:
    command-chain: [bin/wrapper_local]
    command: bin/ireland
    plugs: *standard
  jakarta:
    command-chain: [bin/wrapper_local]
    command: bin/jakarta
    plugs: *standard
  latest:
    command-chain: [bin/wrapper_local]
    command: bin/latest
    plugs: *standard
    environment:
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core
      GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
      GIT_CONFIG_NOSYSTEM: 1
  test-runner:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner
    plugs: *standard
  service:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper service
    daemon: simple
    restart-condition: on-failure
    plugs: *standard
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
    plugs: *standard

parts:
  checkbox-provider-edgex:
    plugin: dump
    source: ./
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox20
    override-build: |
      export PYTHONPATH=$SNAPCRAFT_STAGE/lib/python3.8/site-packages:$SNAPCRAFT_STAGE/usr/lib/python3/dist-packages
      # Comment out for now because it uses old tests to export paths
      # See: https://github.com/canonical/checkbox/blob/8cdd92cb7b02b64d76f4fe474569abb3f0d6f561/checkbox-core-snap/series20/snap/snapcraft.yaml#L397
      # for path in $(find "/snap/checkbox20/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      checkbox-provider-tools validate
      checkbox-provider-tools build
      checkbox-provider-tools install --layout=relocatable --prefix=/providers/checkbox-provider-edgex --root="$SNAPCRAFT_PART_INSTALL"
    stage-packages:
      - lsof
  launchers:
    plugin: dump
    source: launchers/
    organize:
      '*': bin/
  testing-tools:
      plugin: nil
      stage-packages:
        - git
        - golang-1.18-go
        - libcurl4-openssl-dev
        # - curl # this uses libcurl3. adding it causes libssl errors in openssl commands
        # - openssl
        # - libssl-dev
      
